----------------CRIAR TABELA  APRIORI_RULES
DROP TABLE APRIORI_RULES
SELECT *
   INTO  APRIORI_RULES 
  FROM [dbo].[APRIORI] 


UPDATE APRIORI_RULES SET PREVIUS_COMMIT_IS_MY = 'Y' WHERE PREVIUS_COMMIT_IS_MY = 'YES'
UPDATE APRIORI_RULES SET PREVIUS_COMMIT_IS_MY = 'N' WHERE PREVIUS_COMMIT_IS_MY = 'NO'
UPDATE APRIORI_RULES SET FILES = 'E' WHERE FILES = 'EQUAL'
UPDATE APRIORI_RULES SET FILES = 'A' WHERE FILES = 'ADD'
UPDATE APRIORI_RULES SET FILES = 'R' WHERE FILES = 'REM'

UPDATE APRIORI_RULES SET NCLOC = 'E' WHERE NCLOC = 'EQUAL'
UPDATE APRIORI_RULES SET NCLOC = 'A' WHERE NCLOC = 'ADD'
UPDATE APRIORI_RULES SET NCLOC = 'R' WHERE NCLOC = 'REM'


UPDATE APRIORI_RULES SET CLASSES = 'E' WHERE CLASSES = 'EQUAL'
UPDATE APRIORI_RULES SET CLASSES = 'A' WHERE CLASSES = 'ADD'
UPDATE APRIORI_RULES SET CLASSES = 'R' WHERE CLASSES = 'REM'


ALTER TABLE APRIORI_RULES DROP COLUMN CODE_SMELL_QTD
ALTER TABLE APRIORI_RULES DROP COLUMN ID

SELECT *  FROM APRIORI_RULES

drop table APRIORI_RULES


SELECT * FROM Repository2.dbo.RULES where id = '4586'