
DROP TABLE TAGS

SELECT NOME , ROW_NUMBER() OVER (ORDER BY NOME) AS ID  INTO TAGS FROM (
SELECT  DISTINCT ISNULL(A.tags,'NOT_DEFINIED') AS NOME  FROM   [Repository2].[dbo].[ISSUES_SONAR]  A where issue_type = 1
) B



DROP TABLE DN_TAGS_TEMP
CREATE TABLE DN_TAGS_TEMP(
	[ID] INT IDENTITY(1,1) PRIMARY KEY,
	[NAME] VARCHAR(30) NOT NULL
)

DROP TABLE #TAGS
SELECT * INTO #TAGS FROM TAGS 

WHILE ( (SELECT COUNT(0) FROM #TAGS) > 0 )
BEGIN
		DECLARE @ID INT
		DECLARE @VALOR VARCHAR(50)
		SELECT TOP 1 @ID = ID , @VALOR = NOME FROM #TAGS ORDER BY ID
		DELETE #TAGS WHERE ID = @ID
		IF (@VALOR LIKE '%,%')
		BEGIN
			INSERT INTO  DN_TAGS_TEMP  ([NAME])
			SELECT  ELEMENTO FROM FN_SPLITSTRING(@VALOR,',');
		END
		ELSE
			INSERT INTO  DN_TAGS_TEMP  ([NAME]) SELECT  @VALOR
		
END



DROP TABLE DN_TAGS
CREATE TABLE DN_TAGS(
	[ID] INT IDENTITY(1,1) PRIMARY KEY,
	[NAME] VARCHAR(30) NOT NULL
)
INSERT INTO DN_TAGS
SELECT NAME FROM (
SELECT DISTINCT [NAME] FROM DN_TAGS_TEMP
) AS C ORDER BY NAME

SELECT * FROM DN_TAGS

DROP TABLE DN_TAGS_TEMP
DROP TABLE TAGS


SELECT * FROM DN_TAGS
