-----CRIAR TABELA RULES_HASH [RULES_PIVOT] 

SELECT DISTINCT RULE_ID,COMMIT_HASH INTO RULES_HASH FROM ISSUES_SONAR I (NOLOCK) WHERE  I.issue_type = 1
SELECT DISTINCT COMMIT_HASH INTO  [RULES_PIVOT] FROM  RULES_HASH
SELECT DISTINCT RULE_ID INTO RULES_P FROM    RULES_HASH ORDER BY RULE_ID

WHILE ( (SELECT COUNT(0) FROM RULES_P) > 0)
BEGIN
	DECLARE @RULE_ID INT
	SELECT TOP 1 @RULE_ID = RULE_ID FROM RULES_P ORDER BY RULE_ID;
	DELETE RULES_P WHERE RULE_ID = @RULE_ID;

	DECLARE @query VARCHAR(MAX)
	SET @query= 'ALTER TABLE [RULES_PIVOT] ADD R_' +CONVERT(varchar,@RULE_ID) + ' VARCHAR(1);' ; 
	EXECUTE(@query) 
	SET @query= 'update  [RULES_PIVOT] SET R_' +CONVERT(varchar,@RULE_ID) + ' = ''0'';' ; 
	EXECUTE(@query) 
END



SELECT A.* INTO #RULES_HASH FROM RULES_HASH A LEFT JOIN COMMITS B ON A.COMMIT_HASH = B.committer_hash
ORDER BY B.id ASC,A.RULE_ID


WHILE ( (SELECT COUNT(0) FROM #RULES_HASH) > 0)
BEGIN
	DECLARE @COMMIT_HASH VARCHAR(50);
	DECLARE @RULE_ID_B INT;
	SELECT TOP 1 @COMMIT_HASH = COMMIT_HASH , @RULE_ID_B = RULE_ID  FROM #RULES_HASH;
	DELETE #RULES_HASH WHERE COMMIT_HASH = @COMMIT_HASH AND RULE_ID = @RULE_ID_B;

	DECLARE @query_2 VARCHAR(MAX)
	SET @query_2= 'UPDATE RULES_PIVOT SET R_'+CONVERT(varchar,@RULE_ID_B)+' =  (  SELECT COUNT(0) AS T FROM  (SELECT DISTINCT RULE_ID FROM  RULES_HASH WHERE COMMIT_HASH = '''+@COMMIT_HASH+''' AND RULE_ID = '+CONVERT(VARCHAR,@RULE_ID_B)+') AS Q) WHERE  COMMIT_HASH = '''+@COMMIT_HASH+''';' ; 
	EXECUTE(@query_2) 
	PRINT @query_2

END


SELECT *  FROM RULES_PIVOT  where processed = 1
