--DROP TABLE #ISSUE_TAGS_B
SELECT DISTINCT ISNULL(iss.tags,'NOT_DEFINIED') AS TAH ,commitER_hash 
INTO #ISSUE_TAGS_B 
FROM ISSUES I (NOLOCK) JOIN ISSUES_SONAR ISS (NOLOCK)
ON ISS.id =  I.ISSUE_ID
WHERE commitER_hash  IN (
	SELECT COMMITTER_HASH FROM [TIME_SERIES_PREDICT] WHERE CS_aDD > 0 AND  ROW_NUM > 1 AND ROW_NUM <= 4129  AND CS_ACTION = 'ADD'
)


SELECT DISTINCT B.NAME,A.COMMITER_HASH INTO ISSUE_TAGS FROM #ISSUE_TAGS_B A  JOIN  DN_TAGS B ON A.TAH LIKE '%'+B.NAME+'%'
DROP TABLE #ISSUE_TAGS_B

SELECT DISTINCT commitER_hash AS 'COMMITER_HASH'  INTO TAGS_PIVOT FROM ISSUE_TAGS 


SELECT T.TAG ,   ROW_NUMBER() OVER (ORDER BY T.TAG) AS ID   INTO  #ISSUE_TAGS FROM (
SELECT DISTINCT B.NAME AS 'TAG'  FROM ISSUE_TAGS B
) AS T




WHILE ( (SELECT COUNT(0) FROM #ISSUE_TAGS) > 0)
BEGIN
	DECLARE @ID INT
	DECLARE @TAG VARCHAR(50)
	DECLARE @TAG_ORG VARCHAR(50)
	SELECT TOP 1 @ID = ID , @TAG = TAG,  @TAG_ORG = TAG FROM #ISSUE_TAGS ORDER BY ID;
	DELETE #ISSUE_TAGS WHERE @ID = ID;
	DECLARE @query VARCHAR(MAX)

	SET @TAG = REPLACE(@TAG,'-','_')
	SET @query= 'ALTER TABLE [TAGS_PIVOT] ADD T_' +CONVERT(varchar,@TAG) + ' VARCHAR(1);' ; 
	EXECUTE(@query) 
	SET @query= 'update  [TAGS_PIVOT] SET T_' +CONVERT(varchar,@TAG) + ' = ''0'';' ; 
	EXECUTE(@query) 
END


SELECT NAME,COMMITER_HASH, ROW_NUMBER() OVER (ORDER BY T.NAME,COMMITER_HASH) AS ID
INTO #UPDATES 
FROM ISSUE_TAGS T 

WHILE ( (SELECT COUNT(0) FROM #UPDATES) > 0)
BEGIN
	DECLARE @ID_I INT
	DECLARE @COMMITER_HASH VARCHAR(100)
	DECLARE @NAME VARCHAR(50)
	SELECT TOP 1 @ID_I = ID , @NAME = NAME,  @COMMITER_HASH = COMMITER_HASH FROM #UPDATES ORDER BY ID;
	DELETE #UPDATES WHERE @ID_I = ID 

	DECLARE @query_me VARCHAR(MAX)
	SET @NAME = REPLACE(@NAME,'-','_')
	SET @query_me= 'UPDATE [TAGS_PIVOT] SET T_' +CONVERT(varchar,@NAME) + ' =  ''1'' WHERE COMMITER_HASH = '''+@COMMITER_HASH+'''  ' ; 
	EXECUTE(@query_me) 
END

SELECT * FROM #UPDATES 
SELECT C.author_name ,A.* FROM TAGS_PIVOT A JOIN COMMITS C ON C.committer_hash = A.COMMITER_HASH
ORDER BY C.id



